trigger:
- main

pool:
  name: ubuntu-latest

jobs:
- job: Exicute_test
  steps:
  - task: Bash@3
	inputs:
		filePath: './cicd-api.sh' //Generic Shell Script file

  - task: PublishTestResults@2  
	displayName: 'publish testsigma test results'  
	inputs:    
		testResultsFormat: 'Junit'// Test Result Format   
		testResultsFiles: '**/junit-report.xml' //Result File Type
        
