trigger:

- main

pool:

  name: ubuntu-latest

jobs:

- job: Exicute_test

  steps:

    - task: Bash@3

      inputs:

       filePath: './cicd-api.sh' 

    - task: PublishTestResults@2

      inputs:

       testResultsFormat: 'Junit'

       testResultsFiles: '**/junit-report.xml' 
